class_name Globals

extends Node


enum PIECE_COLORS {
	BLACK,
	WHITE
}

enum PIECE_TYPES {
	PAWN,
	ROOK,
	KNIGHT,
	BISHOP,
	KING,
	QUEEN
}

const CELL_SIZE = 16
const TOTAL_PIECES = 32

const STARTING_POSITIONS = [
	# BLACK TOP
	[PIECE_COLORS.BLACK, PIECE_TYPES.ROOK, 0, 0],
	[PIECE_COLORS.BLACK, PIECE_TYPES.KNIGHT, 1, 0],
	[PIECE_COLORS.BLACK, PIECE_TYPES.BISHOP, 2, 0],
	[PIECE_COLORS.BLACK, PIECE_TYPES.QUEEN, 3, 0],
	[PIECE_COLORS.BLACK, PIECE_TYPES.KING, 4, 0],
	[PIECE_COLORS.BLACK, PIECE_TYPES.BISHOP, 5, 0],
	[PIECE_COLORS.BLACK, PIECE_TYPES.KNIGHT, 6, 0],
	[PIECE_COLORS.BLACK, PIECE_TYPES.ROOK, 7, 0],
	
	[PIECE_COLORS.BLACK, PIECE_TYPES.PAWN, 0, 1],
	[PIECE_COLORS.BLACK, PIECE_TYPES.PAWN, 1, 1],
	[PIECE_COLORS.BLACK, PIECE_TYPES.PAWN, 2, 1],
	[PIECE_COLORS.BLACK, PIECE_TYPES.PAWN, 3, 1],
	[PIECE_COLORS.BLACK, PIECE_TYPES.PAWN, 4, 1],
	[PIECE_COLORS.BLACK, PIECE_TYPES.PAWN, 5, 1],
	[PIECE_COLORS.BLACK, PIECE_TYPES.PAWN, 6, 1],
	[PIECE_COLORS.BLACK, PIECE_TYPES.PAWN, 7, 1],
	
	# WHITE BOTTOM
	[PIECE_COLORS.WHITE, PIECE_TYPES.PAWN, 0, 6],
	[PIECE_COLORS.WHITE, PIECE_TYPES.PAWN, 1, 6],
	[PIECE_COLORS.WHITE, PIECE_TYPES.PAWN, 2, 6],
	[PIECE_COLORS.WHITE, PIECE_TYPES.PAWN, 3, 6],
	[PIECE_COLORS.WHITE, PIECE_TYPES.PAWN, 4, 6],
	[PIECE_COLORS.WHITE, PIECE_TYPES.PAWN, 5, 6],
	[PIECE_COLORS.WHITE, PIECE_TYPES.PAWN, 6, 6],
	[PIECE_COLORS.WHITE, PIECE_TYPES.PAWN, 7, 6],
	
	[PIECE_COLORS.WHITE, PIECE_TYPES.ROOK, 0, 7],
	[PIECE_COLORS.WHITE, PIECE_TYPES.KNIGHT, 1, 7],
	[PIECE_COLORS.WHITE, PIECE_TYPES.BISHOP, 2, 7],
	[PIECE_COLORS.WHITE, PIECE_TYPES.QUEEN, 3, 7],
	[PIECE_COLORS.WHITE, PIECE_TYPES.KING, 4, 7],
	[PIECE_COLORS.WHITE, PIECE_TYPES.BISHOP, 5, 7],
	[PIECE_COLORS.WHITE, PIECE_TYPES.KNIGHT, 6, 7],
	[PIECE_COLORS.WHITE, PIECE_TYPES.ROOK, 7, 7]
]

const SPRITE_MAPPING = {
	PIECE_COLORS.BLACK : {
		PIECE_TYPES.PAWN: Vector2i(0, 0),
		PIECE_TYPES.ROOK: Vector2i(0, 1),
		PIECE_TYPES.KNIGHT: Vector2i(0, 2),
		PIECE_TYPES.BISHOP: Vector2i(0, 3),
		PIECE_TYPES.KING: Vector2i(0, 4),
		PIECE_TYPES.QUEEN: Vector2i(0, 5),
	},
	PIECE_COLORS.WHITE : {
		PIECE_TYPES.PAWN: Vector2i(1, 0),
		PIECE_TYPES.ROOK: Vector2i(1, 1),
		PIECE_TYPES.KNIGHT: Vector2i(1, 2),
		PIECE_TYPES.BISHOP: Vector2i(1, 3),
		PIECE_TYPES.KING: Vector2i(1, 4),
		PIECE_TYPES.QUEEN: Vector2i(1, 5),
	}
}
